all: homework4-4 homework4-123 test homework4-5 homework4-6

homework4-123: homework4-123.c ODE.c
	gcc -o homework4-123.exe homework4-123.c ODE.c -lm
test: test.c ODE.c
	gcc -o test.exe test.c ODE.c -lm
homework4-4: homework4-4.c ODE.c
	gcc -o homework4-4.exe homework4-4.c ODE.c -lm
homework4-5: homework4-5.c ODE.c
	gcc -o homework4-5.exe homework4-5.c ODE.c -lm
homework4-6: homework4-6.c ODE.c
	gcc -o homework4-6.exe homework4-6.c ODE.c -lm
