all: problem1 problem2 problem3 problem5 problem6 problem7 problem8 problem9 problem10

problem1: problem1.c 
	gcc -o problem1.exe problem1.c -lm
problem2: problem2.c
	gcc -o problem2.exe problem2.c -lm
problem3: problem3.c
	 gcc -o problem3.exe problem3.c -lgsl -lgslcblas -lm
problem5: problem5.c rootfinding.c
	 gcc -o problem5.exe problem5.c rootfinding.c -lm
problem6: problem6.c rootfinding.c
	 gcc -o problem6.exe problem6.c rootfinding.c -lm
problem7: problem7.c rootfinding.c
	 gcc -o problem7.exe problem7.c rootfinding.c -lm
problem8: problem8.c
	gcc -o problem8.exe problem8.c -lm
problem9: problem9.c rootfinding.c
	gcc -o problem9.exe problem9.c rootfinding.c -lm
problem10: problem10.c rootfinding.c
	gcc -o problem10.exe problem10.c rootfinding.c -lm
