all: problem1 problem2 problem3 problem5 problem6

problem1: problem1.c 
	gcc -o problem1.exe problem1.c -lm
problem2: problem2.c
	gcc -o problem2.exe problem2.c -lm
problem3: problem3.c
	 gcc -o problem3.exe problem3.c -lgsl -lgslcblas -lm
problem5: problem5.c
	 gcc -o problem5.exe problem5.c rootfinding.c -lm
problem6: problem6.c
	 gcc -o problem6.exe problem6.c rootfinding.c -lm
