all: problem5 problem6

problem5: problem5.c approximations.c
	 gcc -o problem5.exe problem5.c approximations.c -lgsl -lgslcblas -lm
problem6: problem6.c approximations.c
	gcc -o problem6.exe problem6.c approximations.c -lgsl -lgslcblas -lm
