all: problem2 problem3 problem4 problem5 

problem2: problem2.c numericalcalc.c approximations.c
	gcc -o problem2.exe problem2.c numericalcalc.c approximations.c -lgsl -lgslcblas -lm

problem3: problem3.c numericalcalc.c approximations.c
	gcc -o problem3.exe problem3.c numericalcalc.c approximations.c -lgsl -lgslcblas -lm

problem5: problem5.c numericalcalc.c
	 gcc -o problem5.exe problem5.c numericalcalc.c -lm
